// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LinkRepo is an autogenerated mock type for the LinkRepo type
type LinkRepo struct {
	mock.Mock
}

type LinkRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkRepo) EXPECT() *LinkRepo_Expecter {
	return &LinkRepo_Expecter{mock: &_m.Mock}
}

// BatchDelete provides a mock function with given fields: ctx, shortURLs, userID
func (_m *LinkRepo) BatchDelete(ctx context.Context, shortURLs []string, userID string) error {
	ret := _m.Called(ctx, shortURLs, userID)

	if len(ret) == 0 {
		panic("no return value specified for BatchDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) error); ok {
		r0 = rf(ctx, shortURLs, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkRepo_BatchDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchDelete'
type LinkRepo_BatchDelete_Call struct {
	*mock.Call
}

// BatchDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - shortURLs []string
//   - userID string
func (_e *LinkRepo_Expecter) BatchDelete(ctx interface{}, shortURLs interface{}, userID interface{}) *LinkRepo_BatchDelete_Call {
	return &LinkRepo_BatchDelete_Call{Call: _e.mock.On("BatchDelete", ctx, shortURLs, userID)}
}

func (_c *LinkRepo_BatchDelete_Call) Run(run func(ctx context.Context, shortURLs []string, userID string)) *LinkRepo_BatchDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string))
	})
	return _c
}

func (_c *LinkRepo_BatchDelete_Call) Return(_a0 error) *LinkRepo_BatchDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkRepo_BatchDelete_Call) RunAndReturn(run func(context.Context, []string, string) error) *LinkRepo_BatchDelete_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinkRepo creates a new instance of LinkRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkRepo {
	mock := &LinkRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
