package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	rootDir := "."

	fileCount := 0

	err := filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			name := info.Name()
			if name != "." && (strings.HasPrefix(name, ".") || name == "vendor" || name == "cmd") {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		if strings.HasSuffix(path, "_gen.go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		fileCount++

		return processFile(path)
	})

	if err != nil {
		fmt.Fprintf(os.Stderr, "Error walking directory: %v\n", err)
		os.Exit(1)
	}

}

func processFile(filePath string) error {
	fset := token.NewFileSet()

	node, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("error parsing file %s: %w", filePath, err)
	}

	structsToReset := findStructsWithResetComment(node)

	if len(structsToReset) == 0 {
		return nil
	}

	return generateResetFile(filePath, fset, node, structsToReset)
}

type StructInfo struct {
	Name   string
	Fields []*FieldInfo
}

type FieldInfo struct {
	Name     string
	Type     string
	IsPtr    bool
	IsSlice  bool
	IsMap    bool
	IsStruct bool
}

func findStructsWithResetComment(node *ast.File) []*StructInfo {
	var structs []*StructInfo

	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}

		hasResetComment := false
		if genDecl.Doc != nil {
			for _, comment := range genDecl.Doc.List {
				if strings.TrimSpace(comment.Text) == "// generate:reset" {
					hasResetComment = true
					break
				}
			}
		}

		if !hasResetComment {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			fields := extractFields(structType)

			structs = append(structs, &StructInfo{
				Name:   typeSpec.Name.Name,
				Fields: fields,
			})
		}
	}

	return structs
}

func extractFields(structType *ast.StructType) []*FieldInfo {
	var fields []*FieldInfo

	if structType.Fields == nil {
		return fields
	}

	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			continue
		}

		for _, name := range field.Names {
			fieldInfo := &FieldInfo{
				Name: name.Name,
			}

			analyzeType(field.Type, fieldInfo)

			fields = append(fields, fieldInfo)
		}
	}

	return fields
}

func analyzeType(expr ast.Expr, fieldInfo *FieldInfo) {
	switch t := expr.(type) {
	case *ast.Ident:
		fieldInfo.Type = t.Name
		if !isBasicType(t.Name) {
			fieldInfo.IsStruct = true
		}

	case *ast.StarExpr:
		fieldInfo.IsPtr = true
		analyzeType(t.X, fieldInfo)

	case *ast.ArrayType:
		if t.Len == nil {
			fieldInfo.IsSlice = true
		}
		analyzeType(t.Elt, fieldInfo)

	case *ast.MapType:
		fieldInfo.IsMap = true

	case *ast.SelectorExpr:
		fieldInfo.Type = fmt.Sprintf("%s.%s", t.X, t.Sel)
		fieldInfo.IsStruct = true

	case *ast.StructType:
		fieldInfo.IsStruct = true
	}
}

func isBasicType(typeName string) bool {
	basicTypes := map[string]bool{
		"int":     true,
		"int8":    true,
		"int16":   true,
		"int32":   true,
		"int64":   true,
		"uint":    true,
		"uint8":   true,
		"uint16":  true,
		"uint32":  true,
		"uint64":  true,
		"float32": true,
		"float64": true,
		"bool":    true,
		"string":  true,
		"byte":    true,
		"rune":    true,
	}
	return basicTypes[typeName]
}

func generateResetFile(filePath string, fset *token.FileSet, node *ast.File, structs []*StructInfo) error {
	dir := filepath.Dir(filePath)

	outputPath := filepath.Join(dir, "reset.gen.go")

	var buf *bytes.Buffer

	fmt.Fprintf(buf, "// Code generated by cmd/reset. DO NOT EDIT.\n\n")
	fmt.Fprintf(buf, "package %s\n\n", node.Name.Name)

	for _, structInfo := range structs {
		generateResetMethod(buf, structInfo)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("error formatting generated code: %w", err)
	}

	err = os.WriteFile(outputPath, formatted, 0644)
	if err != nil {
		return fmt.Errorf("error writing file %s: %w", outputPath, err)
	}

	return nil
}

func generateResetMethod(buf *bytes.Buffer, structInfo *StructInfo) {
	fmt.Fprintf(buf, "func (r *%s) Reset() {\n", structInfo.Name)
	fmt.Fprintf(buf, "\tif r == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n\n")

	for _, field := range structInfo.Fields {
		generateFieldReset(buf, field)
	}

	fmt.Fprintf(buf, "}\n\n")
}

func generateFieldReset(buf *bytes.Buffer, field *FieldInfo) {
	fieldName := field.Name

	if field.IsPtr {
		fmt.Fprintf(buf, "\tif r.%s != nil {\n", fieldName)
		if field.IsSlice {
			fmt.Fprintf(buf, "\t\tr.%s = r.%s[:0]\n", fieldName, fieldName)
		} else if field.IsMap {
			fmt.Fprintf(buf, "\t\tclear(r.%s)\n", fieldName)
		} else if field.IsStruct {
			fmt.Fprintf(buf, "\t\tif resetter, ok := r.%s.(interface{ Reset() }); ok {\n", fieldName)
			fmt.Fprintf(buf, "\t\t\tresetter.Reset()\n")
			fmt.Fprintf(buf, "\t\t} else {\n")
			fmt.Fprintf(buf, "\t\t\t*r.%s = %s{}\n", fieldName, field.Type)
			fmt.Fprintf(buf, "\t\t}\n")
		} else {
			fmt.Fprintf(buf, "\t\t*r.%s = %s\n", fieldName, getZeroValue(field.Type))
		}
		fmt.Fprintf(buf, "\t}\n")
	} else if field.IsSlice {
		fmt.Fprintf(buf, "\tr.%s = r.%s[:0]\n", fieldName, fieldName)
	} else if field.IsMap {
		fmt.Fprintf(buf, "\tclear(r.%s)\n", fieldName)
	} else if field.IsStruct {
		fmt.Fprintf(buf, "\tif resetter, ok := r.%s.(interface{ Reset() }); ok {\n", fieldName)
		fmt.Fprintf(buf, "\t\tresetter.Reset()\n")
		fmt.Fprintf(buf, "\t} else {\n")
		fmt.Fprintf(buf, "\t\tr.%s = %s{}\n", fieldName, field.Type)
		fmt.Fprintf(buf, "\t}\n")
	} else {
		fmt.Fprintf(buf, "\tr.%s = %s\n", fieldName, getZeroValue(field.Type))
	}
}

func getZeroValue(typeName string) string {
	switch typeName {
	case "int", "int8", "int16", "int32", "int64":
		return "0"
	case "uint", "uint8", "uint16", "uint32", "uint64":
		return "0"
	case "float32", "float64":
		return "0"
	case "bool":
		return "false"
	case "string":
		return `""`
	default:
		return typeName
	}
}
