// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LinkRepo is an autogenerated mock type for the LinkRepo type
type LinkRepo struct {
	mock.Mock
}

type LinkRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkRepo) EXPECT() *LinkRepo_Expecter {
	return &LinkRepo_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, url, userID
func (_m *LinkRepo) Add(ctx context.Context, url string, userID string) (string, error) {
	ret := _m.Called(ctx, url, userID)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, url, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, url, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, url, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepo_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type LinkRepo_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - userID string
func (_e *LinkRepo_Expecter) Add(ctx interface{}, url interface{}, userID interface{}) *LinkRepo_Add_Call {
	return &LinkRepo_Add_Call{Call: _e.mock.On("Add", ctx, url, userID)}
}

func (_c *LinkRepo_Add_Call) Run(run func(ctx context.Context, url string, userID string)) *LinkRepo_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *LinkRepo_Add_Call) Return(_a0 string, _a1 error) *LinkRepo_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepo_Add_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *LinkRepo_Add_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinkRepo creates a new instance of LinkRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkRepo {
	mock := &LinkRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
