// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuditEmitter is an autogenerated mock type for the AuditEmitter type
type AuditEmitter struct {
	mock.Mock
}

type AuditEmitter_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditEmitter) EXPECT() *AuditEmitter_Expecter {
	return &AuditEmitter_Expecter{mock: &_m.Mock}
}

// Emit provides a mock function with given fields: action, userID, url
func (_m *AuditEmitter) Emit(action string, userID string, url string) {
	_m.Called(action, userID, url)
}

// AuditEmitter_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type AuditEmitter_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - action string
//   - userID string
//   - url string
func (_e *AuditEmitter_Expecter) Emit(action interface{}, userID interface{}, url interface{}) *AuditEmitter_Emit_Call {
	return &AuditEmitter_Emit_Call{Call: _e.mock.On("Emit", action, userID, url)}
}

func (_c *AuditEmitter_Emit_Call) Run(run func(action string, userID string, url string)) *AuditEmitter_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuditEmitter_Emit_Call) Return() *AuditEmitter_Emit_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuditEmitter_Emit_Call) RunAndReturn(run func(string, string, string)) *AuditEmitter_Emit_Call {
	_c.Run(run)
	return _c
}

// NewAuditEmitter creates a new instance of AuditEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditEmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditEmitter {
	mock := &AuditEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
