\c shortener

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

GRANT ALL PRIVILEGES ON SCHEMA public TO shortener;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO shortener;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO shortener;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO shortener;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO shortener;